### ISSUE TITLE
탭1 search 화면 dispose  에러 확인

### ISSUE THREAD

**Issue by GODueol** [boostcampth/boostcamp3_E#57]
## 개요
-  SearchFragment의  private Disposable disposable; 가 초기화되지않아 onDestory에서 NPE에러 발생

##
- dispoable -> CompositeDisposable 사용 요망
- dispoable시 isdispose()나 !=null 체크 추가 필요

## 에러 전문
2019-02-08 15:28:37.039 4299-4299/com.teame.boostcamp.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.teame.boostcamp.myapplication, PID: 4299
    java.lang.RuntimeException: Unable to destroy activity {com.teame.boostcamp.myapplication/com.teame.boostcamp.myapplication.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4603)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
        at com.teame.boostcamp.myapplication.ui.Search.SearchFragment.onDestroy(SearchFragment.java:127)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2700)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1016)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2605)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2596)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:318)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:354)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:211)
        at com.teame.boostcamp.myapplication.ui.base.BaseActivity.onDestroy(BaseActivity.java:50)
        at android.app.Activity.performDestroy(Activity.java:7471)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4590)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by ho8278** [comment]
해결 완료했습니다!
